### PR TITLE
Fix erroneous RemoteFeatureAction import

### PR DESCRIPTION
**Pull request by annarieger**
S. in title

### CODE REVIEW

**Comment by KaiVolland** [comment]
I don't think that we should use redux stuff in the components at all. There is no `redux` in the `baseclient-components`. I don't know how this even works. I stumbled over this during the work on #439 .

**Comment by annarieger** [comment]
You're right, all redux depending components are extracted into `baseclient-state` packages which lays beside `baseclient-components`. I think, it was intended to separate components from redux stuff by initial baseclient instantiation.

The whole mechanism, how all packages communicate with each other via lerna is still a bit black box for all of us, I think. But the way, how the redux actions can be used inside of components is like shown in this PR. Maybe a one another better approach can be found here, but at the moment I didn't find any other solution how the component can communicate with global state.

**Comment by KaiVolland** [comment]
At least `baseclient-state` needs to be a dependecy i think.

**Comment by annarieger** [comment]
`baseclient-state` is available in `baseclient-components` after it is declared in `index.d.ts` file, no additional dependency install is needed.

https://github.com/terrestris/react-geo-baseclient/blob/master/packages/baseclient-components/index.d.ts#L4

**Comment by KaiVolland** [comment]
>baseclient-state is available in baseclient-components after it is declared in index.d.ts file, no additional dependency install is needed.

This is not an option as you loose all typings of this package. I don't see any benefit of spliting the baseclient into theses three packages as you can`t use the seperately anyways. We should merge them just into one.

**Comment by annarieger** [comment]
I know, you're right.

I think, we should discuss the setup once again with other devs ASAP. The development during last weeks was mostly very  annoying  and slow to go ahead due to endless setup and build issues.

**Comment by marcjansen** [comment]
If removing lerna makes it easier, do it.

If combining into one package makes it easier, do it.

If publishing to npm makes it easier, do it.

Who wants to champion this refactoring?

**Comment by weskamm** [comment]
> Maybe it works because of this: https://github.com/terrestris/react-geo-baseclient/blob/master/packages/baseclient-components/tsconfig.json#L24 which seems to be VERY hackish.

Its the way how we use modules from other packages without duplicating them in every package which speeds up several processes. And yes, its the reason why redux is available in other packages.
When merging the three packages into one, this could be removed of course.


> ~At least `baseclient-state` needs to be a dependecy i think.~
> 
> This doesn't work as it is not on npm of course.

It can be a local dependency and it is, as you can see in the import statements (so no direct need for a npm package). This is something lerna is for, handling dependencies between e.g. multiple local packages.

To conclude, it seems like we are having more issues than advantages through splitting the codebase into multiple packages, so i agree that we can merge them all into one.
Maybe @dnlkoch wants to give some comments in here

**Comment by weskamm** [comment]
> Who wants to champion this refactoring?

Me can do it, just need some time for this!

**Comment by annarieger** [comment]
> > Who wants to champion this refactoring?
> 
> Me can do it, just need some time for this!

I would gladly support you if needed (under the same conditions as you need)

Nevertheless, beside of this surely important discussion, can this PR be merged now or not? Without this fix, the HSI functionality is currently broken on dev-setup.

**Comment by weskamm** [comment]
feel free to merge

**Pull request merged**
