### PR TITLE
Fix handling of URL parameters

### PR DESCRIPTION
**Pull request by weskamm**
Fixes appId detection when more than URL parameter is given.

### CODE REVIEW

**Review by LukasLohoff — APPROVED** [review]

**Comment by weskamm** [comment]
thanks!

**Comment by marcjansen** [comment]
I think support for URL / URLSSearchParams is a bit shaky in IE 11, AFAICT. Do we need to work in this browser?

**Comment by weskamm** [comment]
8 years old browser? i would say no. we may introduce a polyfill if needed in the future

**Comment by marcjansen** [comment]
Fine for me

**Pull request merged**
